### PR TITLE
Added PreferRandomNode

### PR DESCRIPTION
**Pull request by mikaelisik**
Added missing setting in connectionstring

### CODE REVIEW

**Comment by hayley-jean** [comment]
Thank you!

**Comment by gregoryyoung** [comment]
I am curious, what is the benefit of random node? What use case are you trying to solve?

**Comment by mikaelisik** [comment]
We have a number of jobs for rebuilding viewmodels from scratch. When running all of them in parallel and all of them use the same eventstore node, the eventstore node get overloaded. PreferRandomNode helped us distribute the load over all nodes in the cluster.

**Comment by gregoryyoung** [comment]
Unless we are talking about a huge number of projections or running in an iops restricted environment this should not be a huge issue. What is the exact issue you are seeing? A single modern SSD should be able to keep up with the load.

**Comment by mikaelisik** [comment]
We are using VMs on Azure, so it is a IOPS restricted environment, but I don't think that is the problem. 

We are not using projections, we had 6 jobs reading from the all-stream (30M events, ~30GB data). CPU on the eventstore node was 100%. So instead of upgrading each node in the cluster, we distributed the load on all nodes.

**Comment by gregoryyoung** [comment]
This would be interesting to follow up on as you describe an IO based operation and mention that you are at 100% CPU.

**Comment by mikaelisik** [comment]
Could be that I misunderstood the metrics we collected, I need to look into that. 

Anyway, doesn't it make sense to use the slaves to increase read performance instead of scaling up (CPU or IOPS) each node in the cluster?

**Comment by gregoryyoung** [comment]
For reads yes. But on a cluster of 3 as example it won't help much (try running random values 3 times 100,000 times).

**Comment by mikaelisik** [comment]
We actually tried it on a cluster of 3 and saw a decrease of total processing time by ~30%, but that was with ~30M events and 6 processes doing the rebuilds, each one having it's own connection to an eventstore node.

What do you mean by rate of intersection?

**Pull request merged**
