### PR TITLE
Add categories and tags to blog

### PR DESCRIPTION
**Pull request by danjamescrosby**

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
OK @danjamescrosby working again, was some curious bundler bug.

**Comment by danjamescrosby** [comment]
> OK @danjamescrosby working again, was some curious bundler bug.

Awesome, thanks @ChrisChinchilla

**Comment by danjamescrosby** [comment]
@ChrisChinchilla would you mind sense checking this for me? The blog is the major change (the rest is SEO stuff like titles).

**Comment by ChrisChinchilla** [comment]
Looks good. Not sure if it's part of the changes or not, but is worth adding real names to the posts instead of "Event Store Team"?

Also, the title of the blog says "Developer blog", but again, is that just part if what we have now before we separate content properly?

Inline code needs some style to display it better, for example - https://deploy-preview-100--event-store.netlify.com/blog/playing-with-projections/

> Add EVENTSTORE_RUN_PROJECTIONS=All and EVENTSTORE_START_STANDARD_PROJECTIONS=true to your environment variables, or the /etc/eventstore/eventstore.conf configuration file and start Event Store:

Should show the parameter lines more clearly as code. They have some formatting, but not quite clear enough.

Also this tag link - https://deploy-preview-100--event-store.netlify.com/blog/tags/version-3-0/ has odd behaviour, not sure why.

**Comment by danjamescrosby** [comment]
> Looks good. Not sure if it's part of the changes or not, but is worth adding real names to the posts instead of "Event Store Team"?
> 
> Also, the title of the blog says "Developer blog", but again, is that just part if what we have now before we separate content properly?
> 
> Inline code needs some style to display it better, for example - https://deploy-preview-100--event-store.netlify.com/blog/playing-with-projections/
> 
> > Add EVENTSTORE_RUN_PROJECTIONS=All and EVENTSTORE_START_STANDARD_PROJECTIONS=true to your environment variables, or the /etc/eventstore/eventstore.conf configuration file and start Event Store:
> 
> Should show the parameter lines more clearly as code. They have some formatting, but not quite clear enough.
> 
> Also this tag link - https://deploy-preview-100--event-store.netlify.com/blog/tags/version-3-0/ has odd behaviour, not sure why.

Thanks @ChrisChinchilla - I've added a style for the parameter line code blocks so it's a bit clearer. Also fixed the config file, the way the slugs were being created for the tag/category pages wasn't converting some characters to hyphens as expected. The title and overall styling will be updated in the full relaunch. For the authors, we can now define authors in /_data/authors.yml - if a post's author defined in the Frontmatter matches an author in the data file it will pull in their name and bio.

**Pull request merged**
